let SharedSubcriptions = cluster('https://genevareference.westcentralus.kusto.windows.net').database('Shared').DataStudio_ServiceTree_AzureSubscription_Snapshot
|summarize SharedSubscriptions = count() by SubscriptionId, SubscriptionName
|where SharedSubscriptions > 1;
cluster('https://genevareference.westcentralus.kusto.windows.net').database('Shared').DataStudio_ServiceTree_AzureSubscription_Snapshot
| where SubscriptionId in ((SharedSubcriptions | project SubscriptionId))
| project SubscriptionId, SubscriptionName, ServiceId, ServiceName, ServiceLevel 
|sort by SubscriptionName asc, ServiceName asc ;


