ChangeGuard_ExceptionRequest
| distinct ExceptionRequestId, RequestDate, ExceptionRequestStatus, ApproverEmail, LastUpdate, Approvers
| extend TimeSpanToDecision = (LastUpdate - RequestDate)
| extend TimeToDecision_hours = TimeSpanToDecision / 1h
| summarize ExceptionsCount = count() by ExceptionRequestStatus
|union (ChangeGuard_ExceptionRequest
| distinct ExceptionRequestId
| summarize ExceptionsCount = count()
| extend ExceptionRequestStatus = 'TotalExceptions'
)